name: dml
channels:
- defaults
- pytorch
dependencies:
- python=3.9
- pytorch=1.11
- torchvision=0.12
- cudatoolkit=11.3
- pip
- numpy
- jupyter
- matplotlib
- scikit-learn
- scipy
- pandas
- seaborn
- nltk
- h5py
- spacy
- unidecode
- pip:
  - future
  - tb-nightly
  - gym
  - pillow
  - kaggle
  - ipywidgets
